### PR TITLE
Bump versions

### PR DESCRIPTION
**Pull request by takezoe**

### CODE REVIEW

**Comment by takezoe** [comment]
Hmm... Failed with Scala 2.11. Let ne check...

**Comment by magnolia-k** [comment]
@takezoe 

The following error has occurred.

```
Failure(java.lang.AbstractMethodError: Receiver class org.scalatra.SinatraPathPatternParser does not define or inherit an implementation of the resolved method 'abstract scala.util.DynamicVariable scala$util$parsing$combinator$Parsers$$lastNoSuccessVar()' of interface scala.util.parsing.combinator.Parsers.)
```

I think this issue is probably related, but it is unlikely to make it on 2.11 base in new projects, so I think you can remove it from the test.

https://github.com/scala/scala-parser-combinators/issues/197

**Comment by magnolia-k** [comment]
After a little more chasing, Twirl seems to use uniform scala-parser-combinators 1.1.2, and as a result of loading it, it seems to cause the incompatibility that occurs in the combination of 1.1.2 and scala 2.11. Be
The solution seems to be to drop the Scala 2.11 test.

**Comment by takezoe** [comment]
Thanks for checking. Basically, removing Scala 2.11 makes sense.

**Pull request merged**
